version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  user-service:
    build: ./user-service
    ports:
      - "4001:4001"
    depends_on:
      - mongo
      - rabbitmq

  product-service:
    build: ./product-service
    ports:
      - "4002:4002"
    depends_on:
      - mongo
      - rabbitmq

  order-service:
    build: ./order-service
    ports:
      - "4003:4003"
    depends_on:
      - mongo
      - rabbitmq

  graphql-gateway:
    build: ./graphql-gateway
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - product-service
      - order-service
